version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=influencetx
    volumes:
      - data:/var/lib/postgres
  web:
    image: python:3.6.1
    working_dir: /usr/src/app
    command: bash -exc "pip install -r requirements/local.txt && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:5120"
    environment:
      - DATABASE_URL=psql://postgres:mysecretpassword@postgres:5432/influencetx
      - OPENSTATES_API_KEY=${OPENSTATES_API_KEY}
    volumes:
      - .:/usr/src/app
    ports:
      - "5120:5120"
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db:postgres
volumes:
  data:
    driver: local
