# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.IntegerField(db_column='IDNO', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='CTRIB_AMT', decimal_places=4, max_digits=19, null=True)),
                ('date_contributed', models.CharField(blank=True, db_column='CONT_DATE', max_length=27, null=True)),
                ('date_recorded', models.CharField(blank=True, db_column='DATE_RECD', max_length=27, null=True)),
            ],
            options={
                'db_table': 'contribs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.IntegerField(db_column='Ctrib_ID', primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(blank=True, db_column='Employer_ID', db_index=True, null=True)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Surname', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=160, null=True)),
                ('state', models.CharField(blank=True, db_column='StateAbbr', max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=10, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=5, null=True)),
                ('city', models.CharField(blank=True, db_column='CityPreferred', max_length=64, null=True)),
                ('employer', models.CharField(blank=True, db_column='EMPLOYER', max_length=60, null=True)),
                ('occupation', models.CharField(blank=True, db_column='Occupation', max_length=160, null=True)),
                ('interest_code', models.CharField(db_column='InterestCode', max_length=5)),
                ('other_interests', models.CharField(blank=True, db_column='OtherInterests', max_length=255, null=True)),
                ('total_contributions', models.DecimalField(blank=True, db_column='CTRIB_AMT', decimal_places=2, max_digits=11, null=True)),
                ('party', models.CharField(blank=True, db_column='Party', max_length=7, null=True)),
                ('politics', models.CharField(blank=True, db_column='Politics', max_length=8000, null=True)),
                ('dem_score', models.SmallIntegerField(db_column='DemScore')),
            ],
            options={
                'db_table': 'vIdealContributor_v2a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.IntegerField(db_column='iFILER_ID', primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField(blank=True, db_column='iCand_ID', db_index=True, null=True)),
                ('parent_candidate_id', models.IntegerField(blank=True, db_column='iCand_Parent', help_text='Parent id for deduped candidates. Matches candidate_id for non-dupes.', null=True)),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, db_column='firstname', max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, db_column='surname', max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('candidate_name', models.CharField(blank=True, db_column='CandidateName', max_length=290, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('stateabbr', models.CharField(blank=True, db_column='StateAbbr', max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=10, null=True)),
                ('office', models.CharField(blank=True, db_column='Office', max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_column='Party', max_length=5, null=True)),
            ],
            options={
                'db_table': 'vIdealFiler',
                'managed': False,
            },
        ),
    ]
