# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contributionsummary',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contributiontotalbydonor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filer',
            options={'managed': True},
        ),
    ]
