# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='donor',
            field=models.ForeignKey(blank=True, db_column='ctrib_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpj.Donor'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='filer',
            field=models.ForeignKey(blank=True, db_column='iFiler_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpj.Filer'),
        ),
        migrations.AddField(
            model_name='contributionsummary',
            name='donor',
            field=models.ForeignKey(blank=True, db_column='ctrib_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpj.Donor'),
        ),
        migrations.AlterField(
            model_name='contributionsummary',
            name='election_year',
            field=models.IntegerField(blank=True, db_column='eyear', null=True),
        ),
    ]
