# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpj', '0002_change_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributiontotalbyfiler',
            fields=[
                ('filer', models.IntegerField(db_column='ifiler_ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='cycle_total', decimal_places=2, max_digits=19, null=True)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=150, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='StateAbbr', max_length=2, null=True)),
            ],
            options={
                'db_table': 'vfiler_top_donors_2016',
                'managed': False,
            },
        ),
    ]
