# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpj', '0003_contributiontotalbyfiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributionsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, db_column='cycle_total', decimal_places=2, max_digits=19, null=True)),
                ('election_year', models.IntegerField(db_column='eYear')),
            ],
            options={
                'db_table': 'total_donor_filer',
                'managed': False,
            },
        ),
    ]
