# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDisclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('elected_officer', models.CharField(blank=True, max_length=500)),
                ('candidate', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
