# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdisclosure',
            name='leg_id',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, related_name='financial_disclosures', to='legislators.Legislator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialdisclosure',
            name='candidate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialdisclosure',
            name='elected_officer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
