# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-14 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200714_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdisclosure',
            old_name='leg_id',
            new_name='legislator',
        ),
    ]
