# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20200714_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('held_by', models.CharField(choices=[('Filer', 'Filer'), ('Spouse', 'Spouse'), ('Dependent', 'Dependent')], max_length=10)),
                ('num_shares', models.CharField(max_length=100)),
                ('financial_disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='finances.FinancialDisclosure')),
            ],
        ),
    ]
