# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-17 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20200714_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('held_by', models.CharField(choices=[('Filer', 'Filer'), ('Spouse', 'Spouse'), ('Dependent', 'Dependent')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('financial_disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='finances.FinancialDisclosure')),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=100)),
                ('recipient', models.CharField(choices=[('Filer', 'Filer'), ('Spouse', 'Spouse'), ('Dependent', 'Dependent')], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('financial_disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='finances.FinancialDisclosure')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('held_by', models.CharField(choices=[('Filer', 'Filer'), ('Spouse', 'Spouse'), ('Dependent', 'Dependent')], max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('financial_disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='finances.FinancialDisclosure')),
            ],
        ),
    ]
