# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_boards_gifts_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
