# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0002_auto_20170715_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='transparencydata_id',
            field=models.CharField(blank=True, db_index=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='votesmart_id',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
