# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0003_auto_20170716_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislatorIdMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openstates_leg_id', models.CharField(db_index=True, max_length=20)),
                ('tec_filer_id', models.IntegerField()),
            ],
        ),
    ]
