# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 20:48
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.IntegerField(db_column='IDNO', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='CTRIB_AMT', decimal_places=2, max_digits=19, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='CONT_DATE', null=True)),
                ('election_year', models.IntegerField(blank=True, db_column='eYear', null=True)),
            ],
            options={
                'db_table': 'contribs_2018',
                'managed': settings.TPJ_MANAGED,
            },
        ),
        migrations.CreateModel(
            name='Contributionsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(blank=True, db_column='eyear', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='cycle_total', decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'total_donorbyfiler_2018',
                'managed': settings.TPJ_MANAGED,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.IntegerField(db_column='Ctrib_ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='FullName', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Surname', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=10, null=True)),
                ('title', models.CharField(blank=True, db_column='title', max_length=160, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='StateAbbr', max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=10, null=True)),
                ('employer_id', models.IntegerField(blank=True, db_column='Employer_ID', db_index=True, null=True)),
                ('employer', models.CharField(blank=True, db_column='EMPLOYER', max_length=60, null=True)),
                ('occupation', models.CharField(blank=True, db_column='Occupation', max_length=160, null=True)),
                ('interest_code', models.CharField(blank=True, db_column='InterestCode', max_length=5, null=True)),
                ('other_interests', models.CharField(blank=True, db_column='OtherInterests', max_length=255, null=True)),
                ('total_contributions', models.DecimalField(blank=True, db_column='CTRIB_AMT', decimal_places=2, max_digits=11, null=True)),
                ('party', models.CharField(blank=True, db_column='Party', max_length=7, null=True)),
            ],
            options={
                'db_table': 'contributors',
                'managed': settings.TPJ_MANAGED,
            },
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.IntegerField(db_column='iFILER_ID', primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField(blank=True, db_column='iCand_ID', db_index=True, null=True)),
                ('parent_candidate_id', models.IntegerField(blank=True, db_column='iCand_Parent', help_text='Parent id for deduped candidates. Matches candidate_id for non-dupes.', null=True)),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, db_column='firstname', max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, db_column='surname', max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('candidate_name', models.CharField(blank=True, db_column='CandidateName', max_length=290, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='StateAbbr', max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=10, null=True)),
                ('office', models.CharField(blank=True, db_column='Office', max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=100, null=True)),
                ('party', models.CharField(blank=True, db_column='Party', max_length=5, null=True)),
            ],
            options={
                'db_table': 'filers',
                'managed': settings.TPJ_MANAGED,
            },
        ),
        migrations.CreateModel(
            name='Contributiontotalbydonor',
            fields=[
                ('donor', models.OneToOneField(db_column='ctrib_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tpj.Donor')),
                ('election_year', models.IntegerField(blank=True, db_column='eyear', null=True)),
                ('cycle_total', models.DecimalField(blank=True, db_column='cycle_total', decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'total_donor_2018',
                'managed': settings.TPJ_MANAGED,
            },
        ),
        migrations.AddField(
            model_name='contributionsummary',
            name='donor',
            field=models.ForeignKey(blank=True, db_column='ctrib_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpj.Donor'),
        ),
        migrations.AddField(
            model_name='contributionsummary',
            name='filer',
            field=models.OneToOneField(db_column='ifiler_ID', on_delete=django.db.models.deletion.CASCADE, to='tpj.Filer'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='donor',
            field=models.ForeignKey(blank=True, db_column='ctrib_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpj.Donor'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='filer',
            field=models.ForeignKey(blank=True, db_column='iFiler_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='tpj.Filer'),
        ),
    ]
