# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.DateTimeField(blank=True, null=True)),
                ('last', models.DateTimeField(blank=True, null=True)),
                ('passed_lower', models.DateTimeField(blank=True, null=True)),
                ('passed_upper', models.DateTimeField(blank=True, null=True)),
                ('signed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('session', models.IntegerField()),
                ('openstates_bill_id', models.CharField(max_length=20)),
                ('openstates_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('lower', 'lower'), ('upper', 'upper')], max_length=5)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_results', to='bills.Bill')),
                ('no_count', models.ManyToManyField(related_name='no_votes', to='legislators.Legislator')),
                ('other_count', models.ManyToManyField(related_name='other_votes', to='legislators.Legislator')),
                ('yes_count', models.ManyToManyField(related_name='yes_votes', to='legislators.Legislator')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='subjects',
            field=models.ManyToManyField(to='bills.SubjectTag'),
        ),
        migrations.AddField(
            model_name='actiondates',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_dates', to='bills.Bill'),
        ),
    ]
