# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import influencetx.core.constants


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0003_auto_20170716_0315'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[(influencetx.core.constants.Vote('Y'), 'Yay'), (influencetx.core.constants.Vote('N'), 'Nay'), (influencetx.core.constants.Vote('O'), 'Other')], max_length=1)),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='legislators.Legislator')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('lower', 'lower'), ('upper', 'upper')], max_length=5)),
                ('session', models.IntegerField()),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('passed', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('openstates_vote_id', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='voteresult',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='voteresult',
            name='no_count',
        ),
        migrations.RemoveField(
            model_name='voteresult',
            name='other_count',
        ),
        migrations.RemoveField(
            model_name='voteresult',
            name='yes_count',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.ManyToManyField(related_name='bills_sponsored', to='legislators.Legislator'),
        ),
        migrations.DeleteModel(
            name='VoteResult',
        ),
        migrations.AddField(
            model_name='votetally',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_results', to='bills.Bill'),
        ),
        migrations.AddField(
            model_name='singlevote',
            name='vote_tally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bills.VoteTally'),
        ),
    ]
