# Generated by Django 2.2.14 on 2020-08-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200714_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='chamber',
            field=models.CharField(choices=[('House', 'House'), ('Senate', 'Senate')], max_length=6),
        ),
    ]
