# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20170716_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='chamber',
            field=models.CharField(choices=[('lower', 'lower'), ('upper', 'upper')], default='lower', max_length=5),
            preserve_default=False,
        ),
    ]
