# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='bills', to='bills.SubjectTag'),
        ),
    ]
