# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openstates_leg_id', models.CharField(db_index=True, max_length=48)),
                ('name', models.CharField(max_length=45)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('party', models.CharField(choices=[('D', 'Democratic'), ('I', 'Independent'), ('R', 'Republican'), ('U', 'Unknown')], max_length=1)),
                ('chamber', models.CharField(choices=[('House', 'House'), ('Senate', 'Senate')], max_length=6)),
                ('district', models.IntegerField()),
                ('openstates_updated_at', models.DateTimeField()),
                ('url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegislatorIdMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openstates_leg_id', models.CharField(db_index=True, max_length=48)),
                ('tec_filer_id', models.IntegerField()),
            ],
        ),
    ]
