# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('suffixes', models.CharField(blank=True, max_length=35)),
                ('party', models.CharField(choices=[('D', 'Democratic'), ('I', 'Independent'), ('R', 'Republican')], max_length=1)),
                ('chamber', models.CharField(choices=[('lower', 'lower'), ('upper', 'upper')], max_length=5)),
                ('district', models.IntegerField()),
                ('openstates_updated_at', models.DateTimeField()),
                ('openstates_leg_id', models.CharField(db_index=True, max_length=20)),
                ('transparencydata_id', models.CharField(db_index=True, max_length=35)),
                ('votesmart_id', models.CharField(db_index=True, max_length=10)),
                ('url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
            ],
        ),
    ]
