# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='tpj_filer_id',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='legislator',
            name='tx_lege_id',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
    ]
