# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='party',
            field=models.CharField(choices=[('D', 'Democratic'), ('I', 'Independent'), ('R', 'Republican'), ('U', 'Unknown')], max_length=1),
        ),
    ]
