'''
https://capitol.texas.gov/tlodocs/86R/witlistbill/html/HB00864H.htm

This is the a basic test case of witnesses who are:
    For
    On
Registering, but not testifying:
    For
    On
'''

expected_value = [{'name': 'for',
  'witnesses': [{'firstname': 'Royce',
                 'lastname': 'Deaver',
                 'representing': ['Self']},
                {'firstname': 'R.A. "Jake"',
                 'lastname': 'Dyer',
                 'representing': ['Atmos Cities Steering Committee']},
                {'firstname': 'Jose A',
                 'lastname': 'Fiscal',
                 'representing': ['Self']},
                {'firstname': 'Jennifer',
                 'lastname': 'Gates',
                 'representing': ['City of Dallas']},
                {'firstname': 'Clay',
                 'lastname': 'Jenkins',
                 'representing': ['Self']},
                {'firstname': 'Clay',
                 'lastname': 'Jenkins',
                 'representing': ['Dallas County']},
                {'firstname': 'Maria',
                 'lastname': 'Rogers',
                 'representing': ['Self']},
                {'firstname': 'Adrian',
                 'lastname': 'Shelley',
                 'representing': ['Public Citizen']},
                {'firstname': 'Brett',
                 'lastname': 'Shipp',
                 'representing': ['Self']}]},
 {'name': 'against', 'witnesses': []},
 {'name': 'on',
  'witnesses': [{'firstname': 'Stephanie',
                 'lastname': 'Weidman',
                 'representing': ['Railroad Commission of Texas']}]},
 {'name': 'Registering, but not testifying'},
 {'name': 'for_no_testify',
  'witnesses': [{'firstname': 'Donnis',
                 'lastname': 'Baggett',
                 'representing': ['Self', 'Texas Press Association']},
                {'firstname': 'Rita',
                 'lastname': 'Beving',
                 'representing': ['Self']},
                {'firstname': 'Roger',
                 'lastname': 'Davis',
                 'representing': ['Self']},
                {'firstname': 'Sarah',
                 'lastname': 'Davis',
                 'representing': ['Self']},
                {'firstname': 'Deda',
                 'lastname': 'Divine',
                 'representing': ['Self']},
                {'firstname': 'Nattalie',
                 'lastname': 'Glover',
                 'representing': ['Self', 'Big Bend Defense Coalition']},
                {'firstname': 'Ash',
                 'lastname': 'Hall',
                 'representing': ['Self']},
                {'firstname': 'Nan',
                 'lastname': 'Hanus',
                 'representing': ['Self']},
                {'firstname': 'Mike',
                 'lastname': 'Hodges',
                 'representing': ['Texas Press Association']},
                {'firstname': 'Georgia',
                 'lastname': 'Keysor',
                 'representing': ['Self']},
                {'firstname': 'Susan',
                 'lastname': 'Lippman',
                 'representing': ['Self']},
                {'firstname': 'Melissa',
                 'lastname': 'Locke',
                 'representing': ['Texas Real Estate Advocacy & Defense']},
                {'firstname': 'Vanessa',
                 'lastname': 'MacDougal',
                 'representing': ['Self']},
                {'firstname': 'Martha',
                 'lastname': 'Meacham',
                 'representing': ['Self']},
                {'firstname': 'Sally Ann',
                 'lastname': 'Milavc',
                 'representing': ['Self']},
                {'firstname': 'Marcus',
                 'lastname': 'Moncada',
                 'representing': ['Self']},
                {'firstname': 'Lana',
                 'lastname': 'Nance',
                 'representing': ['Bee Spring, LTD']},
                {'firstname': 'Scott',
                 'lastname': 'Nance',
                 'representing': ['Bee Spring, LTD']},
                {'firstname': 'John',
                 'lastname': 'Paris',
                 'representing': ['Atmos Energy Corporation']},
                {'firstname': 'Ender',
                 'lastname': 'Reed',
                 'representing': ['Harris County Commissioners Court']},
                {'firstname': 'Warlan Dominic',
                 'lastname': 'Rivera',
                 'representing': ['Self',
                                  'Environment Texas Research & Policy '
                                  'Center']},
                {'firstname': 'Robin',
                 'lastname': 'Schneider',
                 'representing': ['Texas Campaign for the Environment']},
                {'firstname': 'Arthur',
                 'lastname': 'Simon',
                 'representing': ['Self']},
                {'firstname': 'Riley',
                 'lastname': 'Stinnett',
                 'representing': ['Texas Gas Service']},
                {'firstname': 'Keith',
                 'lastname': 'Wall',
                 'representing': ['CenterPoint Energy']},
                {'firstname': 'Sharon',
                 'lastname': 'Wilson',
                 'representing': ['Self']}]},
 {'name': 'against_no_testify', 'witnesses': []},
 {'name': 'on_no_testify',
  'witnesses': [{'firstname': 'Natalie',
                 'lastname': 'Dubiel',
                 'representing': ['Railroad Commission of Texas']}]}]
